### ISSUE TITLE
Unable to install on OSX

### ISSUE THREAD

**Issue by jakecastillo** [joecannatti/soji#14]
When running
`sudo make install`
after cloning the repository and going to the directory, I was returned,
`make: *** No rule to make target install.  Stop.`

Can somebody potentially shoot me a helping hand?

**Comment by iacobus42** [comment]
@4utnomous I didn't update the readme fully when I filed my PR. I'll get that corrected. 

You can install with `sudo sh install_soji`

**Comment by jakecastillo** [comment]
Thank you so much, I'm so excited to use this.

**Comment by joecannatti** [comment]
Should be easier on the newest version. Reopen if it is not. Thanks!
