### ISSUE TITLE
Accessing the log file

### ISSUE THREAD

**Issue by mannymarco** [joecannatti/soji#16]
I have a strange issue and I am running MacOS. 

If I run `soji start name-of-task`, I am returned
`/Users/<USERNAME>/.config/soji/subcommands/log: line 3: /Users/<USERNAME>/.config/soji/notes/engineering-log-2016-10-29.org: Permission denied`. 

The days log file is not created. Despite this, everything else runs as expected:
- the timer starts
- I get cron jobs every 5 minutes until the 25 are up
- a break is created and the screen dimmed
- the screen brightens after 5 and soji awaits my next input

If I instead run `sudo soji start name-of-task`, this time the log file is created but I am never notified of the time remaining through cron jobs and the pomodoro only ends if I start another. for example, my current pomodoro has reached 50 minutes.

A side issue I have is that of opening the log file by running the `soji` command. I'm unable to use any of the org-mode features. I've set my `$EDITOR` to vi. I can use insert mode, but I have no idea how to access the outline mode and create check lists as shown in your blog post. 

As a work-around I have set my `$EDITOR` to open Sublime Text which is running an orgmode package.

I'm really glad I found Soji, so thank you firstly for creating it, and also for posting it on the [ADHD Programmers Subreddit](https://www.reddit.com/r/ADHD_Programmers/)! Being a programmer with ADHD, I envisage many of the features having a quite transformative effect on my organisation/time management etc. 

I hope you're able to help!

**Comment by iacobus42** [comment]
1) It looks like that when soji installs on OS X it doesn't grant the user write permissions to the `.config/soji` directory. See the issue and possible fix here: https://github.com/joecannatti/soji/issues/12#issuecomment-255537812. 

2) I use vi on OS X. It looks like you need to install an org mode plug-in for Vim, perhaps https://github.com/jceb/vim-orgmode. I haven't installed it yet, so I can't tell you if it works well or not.

**Comment by joecannatti** [comment]
I think this should be cleared up with the newest version. Feel free to reopen if that's not the case.
