### ISSUE TITLE
screen returns to 100% brightness after 1 minute instead of 5 on OS X

### ISSUE THREAD

**Issue by chellberg** [joecannatti/soji#22]
I'm guessing something is not quite right with the os x crontab command. I don't believe I have anything else running that changes the brightness.

I'll dig in and see if I can make some progress after work.

https://github.com/joecannatti/soji/blob/master/subcommands/break

**Comment by joecannatti** [comment]
Did you get this straightened out on OSX?

**Comment by chellberg** [comment]
I didn't make any changes to soji, but I'm not experiencing the issue currently.

**Comment by iacobus42** [comment]
I have the same problem from time-to-time. I notice it happens more frequently when I get up from the computer/move during the break. I don't know is OSX brightness scale depends on the room brightness? That is what I've just assumed and generally ignored the issue when it does happen.

**Comment by chellberg** [comment]
Ooh, interesting observation @iacobus42 - I think I actually did disable auto brightness within this same time period. I bet that was the issue. It wasn't adjusting back up to exactly the previous brightness either, which would make sense if it was autobrightness.

If @joecannatti thinks that'd be worth noting in the README I'd be happy to PR

**Comment by iacobus42** [comment]
@chellberg, I just had a break start and tested it. Getting up and returning to my computer changes the brightness. It is one of the "smart" features of OS X, I'd suppose.
